# Default image (https://hub.docker.com/_/microsoft-dotnet-core-sdk/)
image: mcr.microsoft.com/dotnet/sdk:6.0

stages:
  - build
  - test

before_script:
  - dotnet --version

# Build
build_model:
  stage: build
  script:
    - dotnet build Model
    - dotnet build Persistence

build_view:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:6.0-windowsservercore-ltsc2019
  tags: [windows]
  script:
    - dotnet build robot_fight/robot_fight.sln

# Test
test_model:
  stage: test
  script:
    - dotnet test RobotTest

